//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using FSO.NH.ClasesBase.Core;
using FSO.NH.Core;
namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FastFood.Core.PrecioArticulo))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FastFood.Core.PrecioArticulo))]
    public class AbstractArticulo : DomainObject {
        
        private bool permitePrestamos;
        
        private int plazoPrestamoDias;
        
        private bool permiteStockNegativo;
        
        private string descripcion;
        
        private decimal puntoDePedido;
        
        private FastFood.Core.GrupoArticulo myGrupoArticulo;

        private IList<PrecioArticulo> precioArticulo;


        #region property Codigo
        private string m_Codigo;

        /// <summary>
        /// property column="Codigo" type="String" name="Codigo" not-null="true" 	length="18" /
        /// </summary>
        public virtual string Codigo
        {
            get { return m_Codigo; }
            set
            {
                m_Codigo = value;
            }
        }

        #endregion


        #region property Nombre
        private string m_Nombre;

        /// <summary>
        /// property column="Nombre" type="String" name="Nombre" not-null="true" 	length="50" /
        /// </summary>
        public virtual string Nombre
        {
            get { return m_Nombre; }
            set
            {
                m_Nombre = value;
            }
        }

    
        #endregion


        public virtual bool PermitePrestamos {
            get {
                return this.permitePrestamos;
            }
            set {
                this.permitePrestamos = value;
            }
        }
        
        public virtual int PlazoPrestamoDias {
            get {
                return this.plazoPrestamoDias;
            }
            set {
                this.plazoPrestamoDias = value;
            }
        }
        
        public virtual bool PermiteStockNegativo {
            get {
                return this.permiteStockNegativo;
            }
            set {
                this.permiteStockNegativo = value;
            }
        }
        
        public virtual string Descripcion {
            get {
                return this.descripcion;
            }
            set {
                this.descripcion = value;
            }
        }
        
        public virtual decimal PuntoDePedido {
            get {
                return this.puntoDePedido;
            }
            set {
                this.puntoDePedido = value;
            }
        }
        
        public virtual FastFood.Core.GrupoArticulo MyGrupoArticulo {
            get {
                return this.myGrupoArticulo;
            }
            set {
                this.myGrupoArticulo = value;
            }
        }
        
        public virtual IList<PrecioArticulo> PrecioArticulo {
            get {
                return this.precioArticulo;
            }
            set {
                this.precioArticulo = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class Articulo : AbstractArticulo {
        public override string MiCodigo
        {
            get
            {
                return Codigo;
            }
        }
        public override string MiDescripcion
        {
            get
            {
                return Nombre;
            }
        }
    }
}
