//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FSO.NH.ClasesBase.Core;
namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    public class AbstractComprobante : Parametro {
        
        private FastFood.Core.Numerador numerador;
        
        public virtual FastFood.Core.Numerador Numerador {
            get {
                return this.numerador;
            }
            set {
                this.numerador = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class Comprobante : AbstractComprobante {
    }
}
