//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    public class AbstractCuerpoPedido : CuerpoMovimientoBase {
        
        private int idPedido;
        
        public virtual int IdPedido {
            get {
                return this.idPedido;
            }
            set {
                this.idPedido = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class CuerpoPedido : AbstractCuerpoPedido {
    }
}
