//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FSO.NH.Core;
namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    public class AbstractCuerpoMovimientoBase:DomainObject {
        
        
        

        
        private decimal cantidad;
        
        private decimal precioUnitario;
        
        private decimal totalLinea;

        private ListaDePrecio listaDePrecio;
        
        private decimal precioUnitarioOriginal;

        private Articulo articulo;

        public virtual Articulo Articulo
        {
            get
            {
                return this.articulo;
            }
            set
            {
                this.articulo = value;
            }
        }

        public virtual ListaDePrecio ListaDePrecio
        {
            get
            {
                return this.listaDePrecio;
            }
            set
            {
                this.listaDePrecio = value;
            }
        }
        
        public virtual decimal Cantidad {
            get {
                return this.cantidad;
            }
            set {
                this.cantidad = value;
            }
        }
        
        public virtual decimal PrecioUnitario {
            get {
                return this.precioUnitario;
            }
            set {
                this.precioUnitario = value;
            }
        }
        
        public virtual decimal TotalLinea {
            get {
                return this.totalLinea;
            }
            set {
                this.totalLinea = value;
            }
        }

        
        public virtual decimal PrecioUnitarioOriginal {
            get {
                return this.precioUnitarioOriginal;
            }
            set {
                this.precioUnitarioOriginal = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class CuerpoMovimientoBase : AbstractCuerpoMovimientoBase {
    }
}
