//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FSO.NH.ClasesBase.Core;
using FSO.NH.Core;
namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    public class AbstractPrecioArticulo:DomainObject {
        

        
        private decimal neto;
        
        private FastFood.Core.Articulo articulo;
        
        private FastFood.Core.ListaDePrecio listaDePrecio;
        

        
        public virtual decimal Neto {
            get {
                return this.neto;
            }
            set {
                this.neto = value;
            }
        }
        
        public virtual FastFood.Core.Articulo Articulo {
            get {
                return this.articulo;
            }
            set {
                this.articulo = value;
            }
        }
        
        public virtual FastFood.Core.ListaDePrecio ListaDePrecio {
            get {
                return this.listaDePrecio;
            }
            set {
                this.listaDePrecio = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class PrecioArticulo : AbstractPrecioArticulo {
    }
}
