//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FastFood.Core.DetallePedidos))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FastFood.Core.DetallePedidos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FastFood.Core.PrecioArticulo))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FastFood.Core.PrecioArticulo))]
    public class AbstractArticulo : Parametro {
        
        private decimal precio;
        
        private System.Collections.IList misDetallePedidos;
        
        private System.Collections.IList articulo;
        
        public virtual decimal Precio {
            get {
                return this.precio;
            }
            set {
                this.precio = value;
            }
        }
        
        public virtual System.Collections.IList MisDetallePedidos {
            get {
                return this.misDetallePedidos;
            }
            set {
                this.misDetallePedidos = value;
            }
        }
        
        public virtual System.Collections.IList Articulo {
            get {
                return this.articulo;
            }
            set {
                this.articulo = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class Articulo : AbstractArticulo {
    }
}
