//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FSO_NH.Core;
namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    public class AbstractDetallePedidos:DomainObject {
        
  
        
        private string codigoArticulo;
        
        private string descripcionArticulo;
        
        private decimal cantidad;
        
        private decimal precio;
        
        private decimal totalLinea;
        
        private bool pedido;
        
        private bool tickeado;
        
        private int ordenImpresion;
        
        private FastFood.Core.Articulo miArticulo;
        
        private FastFood.Core.Pedido miPedido;
        

        
        public virtual string CodigoArticulo {
            get {
                return this.codigoArticulo;
            }
            set {
                this.codigoArticulo = value;
            }
        }
        
        public virtual string DescripcionArticulo {
            get {
                return this.descripcionArticulo;
            }
            set {
                this.descripcionArticulo = value;
            }
        }
        
        public virtual decimal Cantidad {
            get {
                return this.cantidad;
            }
            set {
                this.cantidad = value;
            }
        }
        
        public virtual decimal Precio {
            get {
                return this.precio;
            }
            set {
                this.precio = value;
            }
        }
        
        public virtual decimal TotalLinea {
            get {
                return this.totalLinea;
            }
            set {
                this.totalLinea = value;
            }
        }
        
        public virtual bool Pedido {
            get {
                return this.pedido;
            }
            set {
                this.pedido = value;
            }
        }
        
        public virtual bool Tickeado {
            get {
                return this.tickeado;
            }
            set {
                this.tickeado = value;
            }
        }
        
        public virtual int OrdenImpresion {
            get {
                return this.ordenImpresion;
            }
            set {
                this.ordenImpresion = value;
            }
        }
        
        public virtual FastFood.Core.Articulo MiArticulo {
            get {
                return this.miArticulo;
            }
            set {
                this.miArticulo = value;
            }
        }
        
        public virtual FastFood.Core.Pedido MiPedido {
            get {
                return this.miPedido;
            }
            set {
                this.miPedido = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class DetallePedidos : AbstractDetallePedidos {
    }
}
