//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FSO_NH.Core;
namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    public class AbstractParametro:DomainObject {
        

        
        private string codigo;
        
        private string descripcion;
        
        private bool baja;
        
        private string subTipo;
        

        
        public virtual string Codigo {
            get {
                return this.codigo;
            }
            set {
                this.codigo = value;
            }
        }
        
        public virtual string Descripcion {
            get {
                return this.descripcion;
            }
            set {
                this.descripcion = value;
            }
        }
        
        public virtual bool Baja {
            get {
                return this.baja;
            }
            set {
                this.baja = value;
            }
        }
        
        public virtual string SubTipo {
            get {
                return this.subTipo;
            }
            set {
                this.subTipo = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class Parametro : AbstractParametro {
    }
}
