//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FSO_NH.Core;
namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FastFood.Core.DetallePedidos))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FastFood.Core.DetallePedidos))]
    public class AbstractPedido : DomainObject
    {
        

        
        private int nroPedido;
        
        private System.DateTime fecha;
        
        private decimal total;
        
        private decimal descuento;
        
        private decimal paga;
        
        private decimal vuelto;
        
        private decimal totalACobrar;
        
        private string observaciones;
        
        private FastFood.Core.Personal miPersonal;
        
        private System.Collections.IList misDetalles;
        
        private FastFood.Core.Mesa miMesa;
               
        public virtual int NroPedido {
            get {
                return this.nroPedido;
            }
            set {
                this.nroPedido = value;
            }
        }
        
        public virtual System.DateTime Fecha {
            get {
                return this.fecha;
            }
            set {
                this.fecha = value;
            }
        }
        
        public virtual decimal Total {
            get {
                return this.total;
            }
            set {
                this.total = value;
            }
        }
        
        public virtual decimal Descuento {
            get {
                return this.descuento;
            }
            set {
                this.descuento = value;
            }
        }
        
        public virtual decimal Paga {
            get {
                return this.paga;
            }
            set {
                this.paga = value;
            }
        }
        
        public virtual decimal Vuelto {
            get {
                return this.vuelto;
            }
            set {
                this.vuelto = value;
            }
        }
        
        public virtual decimal TotalACobrar {
            get {
                return this.totalACobrar;
            }
            set {
                this.totalACobrar = value;
            }
        }
        
        public virtual string Observaciones {
            get {
                return this.observaciones;
            }
            set {
                this.observaciones = value;
            }
        }
        
        public virtual FastFood.Core.Personal MiPersonal {
            get {
                return this.miPersonal;
            }
            set {
                this.miPersonal = value;
            }
        }
        
        public virtual System.Collections.IList MisDetalles {
            get {
                return this.misDetalles;
            }
            set {
                this.misDetalles = value;
            }
        }
        
        public virtual FastFood.Core.Mesa MiMesa {
            get {
                return this.miMesa;
            }
            set {
                this.miMesa = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class Pedido : AbstractPedido {
    }
}
