//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FastFood.Core.Pedido))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FastFood.Core.Pedido))]
    public class AbstractPersonal : Parametro {
        
        private System.Collections.IList misPedidos;
        
        public virtual System.Collections.IList MisPedidos {
            get {
                return this.misPedidos;
            }
            set {
                this.misPedidos = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class Personal : AbstractPersonal {
    }
}
