//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FSO.NH.Core;
namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    public class AbstractDatosImportacion:DomainObject {
        

        
        private string objeto;
        
        private int idSucursalOrigen;
        
        private int identificadorOrigen;
        
        private int identificadorLocal;
        
        private System.DateTime fechaImportacion;
        
        private int idExportacionOrigen;
        

        
        public virtual string Objeto {
            get {
                return this.objeto;
            }
            set {
                this.objeto = value;
            }
        }
        
        public virtual int IdSucursalOrigen {
            get {
                return this.idSucursalOrigen;
            }
            set {
                this.idSucursalOrigen = value;
            }
        }
        
        public virtual int IdentificadorOrigen {
            get {
                return this.identificadorOrigen;
            }
            set {
                this.identificadorOrigen = value;
            }
        }
        
        public virtual int IdentificadorLocal {
            get {
                return this.identificadorLocal;
            }
            set {
                this.identificadorLocal = value;
            }
        }
        
        public virtual System.DateTime FechaImportacion {
            get {
                return this.fechaImportacion;
            }
            set {
                this.fechaImportacion = value;
            }
        }
        
        public virtual int IdExportacionOrigen {
            get {
                return this.idExportacionOrigen;
            }
            set {
                this.idExportacionOrigen = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class DatosImportacion : AbstractDatosImportacion {
    }
}
