//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    public class AbstractParametro {
        
        private int idParametro;
        
        private string codigo;
        
        private string nombre;
        
        private string subTipo;
        
        private System.DateTime fechaGrabacion;
        
        public virtual int IdParametro {
            get {
                return this.idParametro;
            }
            set {
                this.idParametro = value;
            }
        }
        
        public virtual string Codigo {
            get {
                return this.codigo;
            }
            set {
                this.codigo = value;
            }
        }
        
        public virtual string Nombre {
            get {
                return this.nombre;
            }
            set {
                this.nombre = value;
            }
        }
        
        public virtual string SubTipo {
            get {
                return this.subTipo;
            }
            set {
                this.subTipo = value;
            }
        }
        
        public virtual System.DateTime FechaGrabacion {
            get {
                return this.fechaGrabacion;
            }
            set {
                this.fechaGrabacion = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class Parametro : AbstractParametro {
    }
}
