//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FSO.NH.Core;
using System;
using FSO.NH.ClasesBase.Core;
namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    public class AbstractCliente : Persona {
        private string razonSocial;
        private string direccion;
        private string telefonos;
        private string email;
        private System.DateTime? fechaNacimiento;
        public virtual string RazonSocial {
            get {
                return this.razonSocial;
            }
            set {
                this.razonSocial = value;
            }
        }
        public virtual System.DateTime? FechaNacimiento
        {
            get
            {
                return this.fechaNacimiento;
            }
            set
            {
                this.fechaNacimiento = value;
            }
        }
        public virtual string Direccion
        {
            get {
                return this.direccion;
            }
            set {
                this.direccion = value;
            }
        }        
        public virtual string Telefonos {
            get {
                return this.telefonos;
            }
            set {
                this.telefonos = value;
            }
        }        
        public virtual string Email {
            get {
                return this.email;
            }
            set {
                this.email = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class Cliente : AbstractCliente {
        public override string MiCodigo
        {
            get { return this.NumeroDocumento; }
        }

        public override string MiDescripcion
        {
            get { return this.NombreCompleto + " (" + this.RazonSocial +")"; }
        }
        public virtual string NombreCompleto
        {
            get { return this.Apellido + ", " + this.Nombre ; }
        }
        public virtual void CopyTo(Cliente Copia)
        {
            Copia.Apellido = this.Apellido;
            Copia.Direccion = this.Direccion;
            Copia.Email = this.Email;            
            Copia.FechaNacimiento = this.FechaNacimiento;
            Copia.Nombre = this.Nombre;
            Copia.RazonSocial = this.RazonSocial;
            Copia.Telefonos = this.Telefonos;
        }
    }
}
