//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    public class AbstractCuerpoPedido : CuerpoMovimientoBase {

        private Pedido _Pedido;

        public virtual Pedido Pedido
        {
            get {
                return this._Pedido;
            }
            set {
                this._Pedido = value;
            }
        }
        private bool _Imprime;

        public virtual bool Imprime
        {
            get { return _Imprime; }
            set { _Imprime = value; }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class CuerpoPedido : AbstractCuerpoPedido {
    }
}
