//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using FSO.NH.ClasesBase.Core;
using FSO.NH.Core;
namespace FastFood.Core
{


    [System.SerializableAttribute()]
    public class AbstractMesa: Parametro
    {
        private bool ocupada;

        public virtual bool Ocupada
        {
            get { return ocupada; }
            set { ocupada = value; }
        }
        private bool _SolicitarCantidadOcupantes;

        public virtual bool SolicitarCantidadOcupantes
        {
            get { return _SolicitarCantidadOcupantes; }
            set { _SolicitarCantidadOcupantes = value; }
        }
        private int fila;

        public virtual int Fila
        {
            get { return fila; }
            set { fila = value; }
        }
        private int columna;

        public virtual int Columna
        {
            get { return columna; }
            set { columna = value; }
        }
    }

    [System.SerializableAttribute()]
    public partial class Mesa : AbstractMesa
    {
    }
}

