//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.Core {
    
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FastFood.Core.CuerpoPedido))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FastFood.Core.CuerpoPedido))]
    public class AbstractPedido : MovimientoBase {
        
        private bool pendiente;
        
        private decimal pagaCon;
        
        private decimal vuelto;
        
        private decimal descuentoRecargo;
        
        private System.Collections.IList cuerpoPedido;
        
        private FastFood.Core.Mesa mesa;
        private int ocupantes;

        public virtual int Ocupantes
        {
            get { return ocupantes; }
            set { ocupantes = value; }
        }
        public virtual bool Pendiente {
            get {
                return this.pendiente;
            }
            set {
                this.pendiente = value;
            }
        }
        
        public virtual decimal PagaCon {
            get {
                return this.pagaCon;
            }
            set {
                this.pagaCon = value;
            }
        }
        
        public virtual decimal Vuelto {
            get {
                return this.vuelto;
            }
            set {
                this.vuelto = value;
            }
        }
        
        public virtual decimal DescuentoRecargo {
            get {
                return this.descuentoRecargo;
            }
            set {
                this.descuentoRecargo = value;
            }
        }
        
        public virtual System.Collections.IList CuerpoPedido {
            get {
                return this.cuerpoPedido;
            }
            set {
                this.cuerpoPedido = value;
            }
        }
        
        public virtual FastFood.Core.Mesa Mesa {
            get {
                return this.mesa;
            }
            set {
                this.mesa = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public partial class Pedido : AbstractPedido {
        public virtual string ClienteNombre
        {
            get { return Cliente.NombreCompleto; }
        }
        public virtual string MesaDescripcion
        {
            get { return Mesa.Nombre; }
        }
        public virtual string UsuarioDescripcion
        {
            get { return Usuario.UserName; }
        }
        public virtual string EstadoDescripcion
        {
            get { return  Activo?"Activo":"Anulado" ; }
        }
    }
}
